name: sake
favicon: null
layout_spectrum: 0.01499
typography_spectrum: 0.5696555392351002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1919'
    - '#76b3be'
    - '#c80026'
    - '#d74863'
  brandStrength: 0.8125
  lightness: 0.11559088854119182
  saturation: 0.10994681296870112
  rhythmicContrast: 0.9580976217985153
purpose: []
