name: SAKE SUMO BLOG
favicon: null
layout_spectrum: 0.00265
typography_spectrum: 0.59877
title: 'SAKE SUMO BLOG '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1919'
    - '#76b3be'
    - '#c80026'
    - '#d74863'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
